"""Git hook generation."""

from __future__ import annotations

import stat
from pathlib import Path

_PRE_COMMIT_SCRIPT = """\
#!/usr/bin/env bash
# secretleak pre-commit hook
# Auto-generated by: secretleak install-hook
# Blocks commits when secrets are detected in staged files.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Resolve the secretleak binary
if command -v secretleak &>/dev/null; then
    SCANNER="secretleak"
elif [ -f "${REPO_ROOT}/.venv/bin/secretleak" ]; then
    SCANNER="${REPO_ROOT}/.venv/bin/secretleak"
else
    echo "[secretleak] WARNING: secretleak not found in PATH; skipping secret scan."
    exit 0
fi

echo "[secretleak] Scanning staged files for secrets..."

# Run the staged scan; exit code 1 means findings, 0 means clean
if ! "$SCANNER" scan --staged --no-color "${REPO_ROOT}"; then
    echo ""
    echo "[secretleak] !! Commit BLOCKED: secrets detected in staged files."
    echo "[secretleak]    Review the findings above and either:"
    echo "[secretleak]      • Remove/rotate the secret, then re-stage."
    echo "[secretleak]      • Add to allowlist in .secretleak.yaml if false positive."
    echo "[secretleak]      • Run: secretleak generate-baseline to suppress known findings."
    exit 1
fi

echo "[secretleak] No secrets found. Proceeding with commit."
exit 0
"""


def install_pre_commit_hook(repo_path: Path, force: bool = False) -> Path:
    """Write the pre-commit hook script and make it executable.

    Args:
        repo_path: Root of the git repository.
        force: Overwrite an existing hook if present.

    Returns:
        Path to the installed hook script.

    Raises:
        FileExistsError: If a hook already exists and `force` is False.
        RuntimeError: If `.git/hooks` directory doesn't exist.
    """
    hooks_dir = repo_path / ".git" / "hooks"
    if not hooks_dir.is_dir():
        raise RuntimeError(
            f"No .git/hooks directory found at '{hooks_dir}'. Is this a git repository?"
        )

    hook_path = hooks_dir / "pre-commit"

    if hook_path.exists() and not force:
        raise FileExistsError(
            f"A pre-commit hook already exists at '{hook_path}'. Use --force to overwrite."
        )

    hook_path.write_text(_PRE_COMMIT_SCRIPT)
    hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return hook_path


def uninstall_pre_commit_hook(repo_path: Path) -> bool:
    """Remove the pre-commit hook if it was installed by secretleak.

    Returns True if removed, False if not present or not ours.
    """
    hook_path = repo_path / ".git" / "hooks" / "pre-commit"
    if not hook_path.exists():
        return False
    content = hook_path.read_text()
    if "secretleak pre-commit hook" not in content:
        return False  # Not ours – leave it alone
    hook_path.unlink()
    return True
